apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  selector:
    app: {{ include "backend.fullname" . }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
