apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-bpce-platform.yaml
  - kafkanodepool-bpce-kafka-pool.yaml
  - kafka-bpce-kafka.yaml
  - kafkatopic-bpce-events.yaml
  - kafkauser-bpce-app.yaml
